apiVersion: v1
kind: ConfigMap
metadata:
  name: sentiment-ledger-config
data:
  application.properties: |
    spring.application.name=sentiment-ledger
    logging.level.com.daya.project.sentiment_ledger=INFO
    sentiment-ledger.search.top-k=3
    management.endpoints.web.exposure.include=metrics,prometheus,health,info