apiVersion: v1
kind: Service
metadata:
  name: sentiment-ledger-service
spec:
  selector:
    app: sentiment-ledger
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: metrics
      port: 9090
      targetPort: 9090
  type: LoadBalancer